#!/bin/bash
if [ -f /home/$USER/.config/chromium/Default/Preferences ]; then
  sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' /home/$USER/.config/chromium/Default/Preferences
fi
if [ -f /home/$USER/.config/chromium/Default/Preferences ]; then
  sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' /home/$USER/.config/chromium/Default/Preferences
fi
xset s noblank
xset s off
xset -dpms
/usr/bin/chromium-browser --noerrdialogs --disable-infobars --kiosk http://127.0.0.1:32500/
